version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: invisibleprogrammer
      POSTGRES_PASSWORD: invisiblepassword
      POSTGRES_DB: invisibleurl-db
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
