DO $$ BEGIN

RAISE NOTICE 'Creating table "Users"...';
create table users (
    user_id bigint generated by default as identity not null,
    external_id uuid not null,
    email_address varchar(255) not null,
    password_hash varchar(100) not null,
    user_status smallint not null,
    constraint pk_users primary key (user_id)
);

create index idx_users_external_id on users (external_id);
create index idx_users_email_address on users (email_address, user_status);

RAISE NOTICE 'Creating table "ShortUrls"...';
create table short_urls (
    short_url_id bigint generated by default as identity (start with 20000000 increment by 1) not null,
    user_id bigint not null,
    full_url varchar(2000) not null,
    short_url varchar(50) null,
    constraint pk_short_urls primary key (short_url_id)
);

create unique index uniq_short_urls_short_url on short_urls (short_url);

create index idx_short_urls_user_id on short_urls (user_id);

END $$;
